# Dockerfile
FROM oel20/cvrunner-base-arm:latest

# Copy dependency file first for caching
COPY poetry.lock* requirements.txt* /workspace/

# Install dependencies
RUN pip install --no-cache-dir -U pip \
    && if [ -f requirements.txt ]; then pip install -r requirements.txt; fi \
    && if [ -f poetry.lock ]; then pip install poetry && poetry install --no-dev; fi

COPY . /workspace

# Set working directory
WORKDIR /workspace

# Set default entrypoint to cvrunner CLI
ENTRYPOINT ["cvrunner"]
